### ISSUE TITLE
No way to move the print before taking the picture.

### ISSUE THREAD

**Issue by Rolodo** [taxilian/OctoPrint-Twilio#14]
It would be nice to be able to send GCode right before your plugin execute the SMS and picture script, that way I would be able to center my bed so the print is in the picture. Currently my printer put the bed at the max on Y so most of the time I don't even see the print in the picture.

Thanks, I love the plugin you made :)

P.S. I tryed to put the GCode in the GCode script : "After print job completes", but your plugin execute before this command.

**Comment by shadycuz** [comment]
Hey @Rolodo, 

Storing and sending custom gcode is beyond the scope of this plugin. I have observed in my own prints in the past that the finishing gcode does not get run until after the printing is finished. I have opened an issue with Octoprint to see if we can fix the current event or maybe get a new event.

**Comment by shadycuz** [comment]
@Rolodo I have added a [feature ](https://github.com/OctoPrint/OctoPrint/pull/3903) to OctoPrint that will send out events for the predefined GCODE scripts. When its released in `1.6.0` you will be able to update to `OctoPrint-Twilio v1.0.0` and configure the plugin to take a picture and send the SMS after you have repositioned your printer. 

Even though `1.6.0` is still not out, could you help me test the `PrintDone` event? 

You can install the new version to your printer using this url `https://github.com/taxilian/OctoPrint-Twilio/archive/events.zip`. To do that just go into plugin manager and then click `get more`. Then find the `... from URL` section.

![image](https://user-images.githubusercontent.com/17090999/100519842-6d2bc900-31c0-11eb-983e-fd46538523ea.png)

Then just click install. Octoprint will ask you to reload and then it should work. Sometimes when you open the settings page for plugin that changes the GUI you might have to `shift + f5` and/or restart your OctoPrint server (to force it to rebundle the frontend).
