### ISSUE TITLE
Plugin config blank

### ISSUE THREAD

**Issue by hrmtacos** [taxilian/OctoPrint-Twilio#17]
Plugin is installed, octoprint reloaded, but the plugin configuration is totally blank.

**Comment by ski113** [comment]
same issue with me

**Comment by shadycuz** [comment]
Did you get this resolved? A lot of times this is an issue with the browser cache. Shift + f5 usually fixes it in chrome. 

One time I had this happen and I had to remove and re-install the plugin. 

If this keeps happening I can try and investigate it but it would help to have the logs. 

Closing for now, we can always re-open.
