### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wallygator7744** [taxilian/OctoPrint-Twilio#2]
Would it be possible to add a picture to the sms message? And if so how about a progress report and picture at 15,50 and 75 percent?

**Comment by shadycuz** [comment]
I'm working on a PR right now for MMS (picture msg). Let me get that completed and then we can probably add something for progress.

**Comment by taxilian** [comment]
sounds awesome; I don't have a lot of time to work on this right now, but I'm happy for others to join in and add some features!

**Comment by shadycuz** [comment]
Okay cool =). I guess I'll switch the event to upload for testing and then
before I submit the PR I'll test everything on my printer.

Thanks

**Comment by shadycuz** [comment]
I think I'm going to try to print a empty gcode file that has like a single move command. That should work.
