### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by VeryKross** [taxilian/OctoPrint-Twilio#22]
Please add Python 3 Compatibility as outlined [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html).

**Comment by smeisner** [comment]
+1

**Comment by shadycuz** [comment]
I do not have the printer any longer but I do have maintainer access in PyPI for this project. I can use the octoprint simulator to do the dev work but I may need help from someone to do some actual testing on their printer.

**Comment by smeisner** [comment]
I will certainly test this!

**Comment by shadycuz** [comment]
@smeisner @VeryKross 

You can install the new version to your printer using this url `https://github.com/taxilian/OctoPrint-Twilio/archive/feat/python3.zip`. To do that just go into plugin manager and then click `get more` at the very bottom of the list. After you click `get more` you will need to grab the scroll bar and move it to the bottom of the screen, dont scroll inside the long list of plugins ;) 

![image](https://user-images.githubusercontent.com/17090999/100519842-6d2bc900-31c0-11eb-983e-fd46538523ea.png)


Insert the URL above and you should be able to install and test version `0.4.0` that has python3 support. I tested the SNS part and that worked for me but I do not have a printer and camera to test the picture part. 

You can also open up your gcode file and take most of it out but like the first 3 lines. That way you can "print" with out actually printing if you want too.

**Comment by smeisner** [comment]
Shortly after I said I'd test this update, I started a print that is going to take a number of hours. So as soon as it's done, I will test your fix.

**Comment by shadycuz** [comment]
No problem =)

**Comment by shadycuz** [comment]
Python3 compatible release is out. https://pypi.org/project/OctoPrint-Twilio/0.4.0/
