### ISSUE TITLE
Dev Question: How do I trigger a fake event?

### ISSUE THREAD

**Issue by shadycuz** [taxilian/OctoPrint-Twilio#4]
I'm wanting to learn more about octoprint so I decided to add a feature to your plugin. I have set up my development environment using the provided octoprint instructions.  The only thing I haven't been able to figure out is how to generate a fake "PrintDone" event so I can test things. 

Thanks,
Levi

**Comment by taxilian** [comment]
Unfortunately, I don't actually have any idea either =]

I did this because I needed it and I just modified an existing plugin which didn't have a "fake event" helper either.  I got it working and haven't hardly touched it since... =]

**Comment by shadycuz** [comment]
@taxilian I used a empty gcode file with one command like turn of fan `m107`
